services:
  - type: web
    name: animedekho-api
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt && playwright install-deps && playwright install firefox"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: POETRY_VENV_PATH
        value: /opt/render/project/src/.venv